version: '3.7'

services:
  api:
    build: api/
    command: gunicorn -c gun.py server:app
    ports:
      - 2345:2345
    environment:
      - BLOG_SERVER_ENV=product
      - HOST_ID=001
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    container_name: api
    volumes:
      - "/data/blog:/var/log/tissue"
      - "/etc/localtime:/etc/localtime"
    restart: always
  cworker:
    build: api/
    command: celery worker -A app.celery_task -P gevent -c 5 --uid www --gid www
    environment:
      - BLOG_SERVER_ENV=product
      - HOST_ID=001
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    container_name: worker
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/root/.ssh/id_rsa:/home/www/id_rsa"
    restart: always